### ISSUE TITLE
Verbatim prompts and action in GPT builder?

### ISSUE THREAD

**Issue by StefKirsch** [UB-Mannheim/FAIR-GPT#1]
Can you add all text and code you entered into the GPT builder? This would be really interesting, also as a template on how to build GPTs that interact with APIs.
This also makes it possible to contribute code and for people to build test versions themselves.

**Comment by renat-kaufmann** [comment]
I've added instructions and action for re3data to https://github.com/UB-Mannheim/FAIR-GPT/tree/main/GPT.
