### ISSUE TITLE
Wrong description in your Readme

### ISSUE THREAD

**Issue by albangaignard** [UB-Mannheim/FAIR-GPT#4]
In the README file, the description of FAIR-Checker seems to be a bit too creative : _"Retrieves current weather data for a location"_. 

Thanks anyway for your talk at Elixir All-Hands meeting 2024, and for using FAIR-Checker :-)

**Comment by renat-kaufmann** [comment]
ha-ha, thank you for your comment, will fix it tomorrow :-)
